/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    TodoList: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "text",
              type: "string",
            },
          ],
          name: "TaskAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "completed",
              type: "bool",
            },
          ],
          name: "TaskToggled",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_text",
              type: "string",
            },
          ],
          name: "addTask",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "getTasks",
          outputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "text",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "completed",
                  type: "bool",
                },
              ],
              internalType: "struct TodoList.Task[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_index",
              type: "uint256",
            },
          ],
          name: "toggleTask",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
